name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zenobiusztasak/automating-web:dev

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: root
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            cd ~/automating-web
            docker pull zenobiusztasak/automating-web:dev
            docker compose stop
            docker compose up -d
